/* World definitions. Each one changes the look, the lighting, how big the
   maze gets and what is hunting you in it. */

const Worlds = {
  order: ['w1', 'w2'],

  w1: {
    id: 'w1',
    name: 'Stone Maze',
    blurb: 'Cold stone under moonlight. One hunter.',
    tag: 'Normal',
    sizeScale: 1,
    wallHeight: 3.4,
    palette: {
      stoneBase: '#4a4a52',
      stoneBlock: [62, 26],          // [base grey, random spread]
      stoneMortar: 'rgba(0,0,0,0.25)',
      ground: '#2b2f36',
      groundSeam: 'rgba(0,0,0,0.28)',
      sky: ['#0b1026', '#1c2748', '#3a3f5c'],
      stars: true,
      fog: 0x141a2e,
      fogDensity: 0.045,
      hemiSky: 0x8ea2d0,
      hemiGround: 0x2b2f36,
      hemiPower: 0.55,
      sunColor: 0xbcd0ff,
      sunPower: 0.85,
      torchColor: 0xffd9a0,
      torchPower: 1.5,
      torchRange: 16,
      portal: 0x22c55e,
      portalGlow: 0x4ade80,
    },
    /* who is in here, and how fast they move */
    pack: { big: 1, mini: 0 },
    hunter: { small: 3.9, medium: 4.5, large: 5.1 },
    grace: { small: 5, medium: 4, large: 3.5 },
    intercept: { small: false, medium: true, large: true },
  },

  w2: {
    id: 'w2',
    name: 'The Foundry',
    blurb: 'Molten dark, bigger maze, a pack of them — and the small ones are quick.',
    tag: 'Brutal',
    sizeScale: 1.4,
    wallHeight: 4.4,
    palette: {
      stoneBase: '#3a2320',
      stoneBlock: [52, 30],
      stoneMortar: 'rgba(120,20,0,0.35)',
      ground: '#241411',
      groundSeam: 'rgba(180,50,10,0.22)',
      sky: ['#180404', '#3d0f0a', '#83310f'],
      stars: false,
      fog: 0x1c0806,
      fogDensity: 0.075,
      hemiSky: 0xff8a5c,
      hemiGround: 0x1a0a08,
      hemiPower: 0.4,
      sunColor: 0xffb27a,
      sunPower: 0.5,
      torchColor: 0xffae6a,
      torchPower: 1.2,
      torchRange: 13,
      portal: 0x38bdf8,
      portalGlow: 0x7dd3fc,
    },
    pack: { big: 2, mini: 3 },
    hunter: { small: 4.4, medium: 5.0, large: 5.5 },
    grace: { small: 4, medium: 3.2, large: 2.8 },
    intercept: { small: true, medium: true, large: true },
  },
};
